### ISSUE TITLE
Need admin right

### ISSUE THREAD

**Issue by JooSeng6** [Wilenty/InnoSetup_6.3.x_-_6.4.x-dev_Unpacker-Extractor_#1]
Can you remove the need of admin right to run? I do not think it is require for extracting an installer.

**Comment by Wilenty** [comment]
Hello @JooSeng6,
this is the default setting of InnoSetup compiler, but I will change it in next release.

Greetings,
Wilenty

**Comment by Wilenty** [comment]
Hello @JooSeng6,
as promised, changed it in this release: https://github.com/Wilenty/InnoSetup_6.3.x_-_6.4.x-dev_Unpacker-Extractor_/releases/tag/v2.0

Greetings,
Wilenty
