### ISSUE TITLE
v2.0 runtime error when unpack

### ISSUE THREAD

**Issue by raddyst** [Wilenty/InnoSetup_6.3.x_-_6.4.x-dev_Unpacker-Extractor_#2]
When unpack https://files3.codecguide.com/klcp_update_1849_20240731.exe - InnoSetup_6.3.x_-_6.4.x-dev_Unpacker-Extractor crashes with runtime error: 

FastDuplicatesExtraction & IgnoresDuplicatesButStoresEntriesToFirstDuplicate

Runtime error (at 50:1048): The filename, directory name, or volume label syntax is incorrect

![зображення](https://github.com/user-attachments/assets/4f7b1c25-e963-4677-a7cb-08908ebc6fc2)

**Comment by Wilenty** [comment]
Hello @raddyst,
thank you for reporting this issue.
I forgot about InnoSetup special characters - not allowed in real path.
I will fix it, I hope in this week, and let you know.

Greetings,
Wilenty

**Comment by raddyst** [comment]
> I will fix it, I hope in this week, and let you know.

It's not urgent, i just compared the results of unpacking innoextractor/innounp/InnoSetup_6.3.x_-_6.4.x-dev_Unpacker-Extractor a random file.

**Comment by Wilenty** [comment]
Hello @raddyst.

At the outset.
> (...) i just compared the results of unpacking innoextractor/innounp/InnoSetup_6.3.x_-_6.4.x-dev_Unpacker-Extractor a random file.

Extracting: https://download.gimp.org/gimp/v2.10/windows/gimp-2.10.38-setup.exe
by InnoExtractor it's quite fast, but the result files are 32-bit (x86) only.
And, InnoExtractor does not support latest InnoSetup 6.3.x and up:
![innoextract-1 9-windows](https://github.com/user-attachments/assets/1a80f370-c8e0-461f-9ec3-958a473d4c3d)
So it can't take a part in the comparison.

Fixed reported bug and changed special characters to: #
Also it will better process {code:(...)} in the filenames.
https://github.com/Wilenty/InnoSetup_6.3.x_-_6.4.x-dev_Unpacker-Extractor_/releases/tag/v2.01

I also have something for you to compare, if you wish.
File: https://files3.codecguide.com/K-Lite_Codec_Pack_1848_Mega.exe
PW: MLHSPuHkoK2tLgnz6bFN5wnpT0nRHXCM2PCoFLF6n5PTCHP2PFInICCP4I045IoX

If above release fixed this issue, please close it.
But, if you have any additional questions, we can talk here (except from where I got the password to the K-Lite).

Greetings,
Wilenty

P.S.
https://cdn.discordapp.com/attachments/645144950672982027/1269247275968761909/forraddyst.7z?ex=66af5e24&is=66ae0ca4&hm=977a8b3bc738d05c5f8519bf1aef77a22bde9f5f255f651aca4b901ddb106969&
