### ISSUE TITLE
Access violation error extracting Beyond Compare installer

### ISSUE THREAD

**Issue by Breamer** [Wilenty/InnoSetup_6.3.x_-_6.4.x-dev_Unpacker-Extractor_#3]
When trying to extract Beyond Compare 5.0.4 installer (https://www.scootersoftware.com/files/BCompare-5.0.4.30422.exe) I'm getting an access violation error.

![image](https://github.com/user-attachments/assets/eff0386f-3d3a-420b-9969-5c80aba16617)

**Comment by Wilenty** [comment]
Hello @Breamer.

If you will try to extract above mentioned installer with the InnoUnp by JR, you will see something like this:
![InnoUnp](https://github.com/user-attachments/assets/23f68aa2-2861-4b32-a38f-e36b82d8aab8)

So, it means this is a Custom Installer (compiled by them with additional options), or it's somehow protected from unpacking.
My script just shows the error directly from the code, but InnoUnp catches it and displays message about incorrect installer.

Most of unpacker/extractor here extracts only standard installers (with one exception).

Greetings,
Wilenty
